### ISSUE TITLE
Lot of debug outputs

### ISSUE THREAD

**Issue by vincentbernat** [aunetx/deezer-linux#10]
Hey!

I am running the Flatpak version and the app is quite verbose with many log lines like `23:24:01.470 (main/debug) ›  Added response headers for https://e-cdnt-proxy-4.dzcdn.net`. This is logged in the `~/.xsession-errors` file in my case. Is it possible to disable debug logs?

**Comment by aunetx** [comment]
Hello, I saw that the app was verbose, but it looks like this is just the way it works (deezer devs did seem to care a looott about debugging their user's apps... :p)

To be honest, idk how this works; there seems to be a global logging system (as in my case journald does all the work, I guess you're not running systemd?)

I will see what I can do to maybe patch some parts of the code, to have less outputs ; however I need to be pretty careful about it if I don't want to break everyone's music session :)

**Comment by vincentbernat** [comment]
I am also using systemd, but I am worried it could fill up the journal pretty quickly when enabling the offline mode for example. I'll investigate a bit when I find some time, don't bother.

**Comment by aunetx** [comment]
Okay, thanks a lot :p
(ça fait marrant de voir un français !)

**Comment by StollD** [comment]
I might be able to help with this. When I looked through the source code of the app for #9, I saw that there is a function called `isDev()`, that returns whether the app runs in a development environment or not. Now, they use this function like this:
```js
this.foo = isDev() ? <devel_behaviour> : <prod_behaviour>;
```
But a few times this is done instead:
```js
this.bar = isDev ? <devel_behaviour> : <prod_behaviour>;
```
I believe this is an error by the developers, because the second code never invokes the `isDev` function, it only checks if the symbol exists. Because that is always the case, the app will always choose the development behaviour, which could include the excessive logging.
