### ISSUE TITLE
Why you don't make own client with the Deezer API?

### ISSUE THREAD

**Issue by carrieroent** [aunetx/deezer-linux#35]
Hey, I don't want to belittle your work or anything, but why you doing this and not your own client with the Deezer API? Of course, Deezer Windows porting is also important, it brings the Deezer (almost) official app to Linux, but still Deezer to Linux has been wanted for years and I can't understand why no one just makes client for Linux with the Deezer API, something like [Spot](https://github.com/xou816/spot)? Or doesn't Deezer's API allow this? https://developers.deezer.com/api, https://developers.deezer.com/

**Comment by vvitez** [comment]
I'm guessing one reason for this is that, as far as I understand from the api docs, it doesn't help with playback in any way, you just get basic info about tracks, albums, artists, and can add/remove them. There's nothing in there about playing them apart from conatining a link to the original source. Now that's even maybe enough for playback of a song if you then have a http request to that thing and streaming the audio (might mean that you need electron, though, which would kinda defeat the purpose). But even more of a pain in the bum would be that you then can't download the songs as far as i understand. 
I think the main reason for why they opened up this api is so that people can code up their own translators from spotify/apple music/other providers to port over their favourite songs and playlists.

Take all of this with a few grains of salt though, since I might be entirely wrong on everything I just wrote.

**Comment by aunetx** [comment]
Hello, thanks for the answer, unfortunately what I am doing here is extremely far from creating my own client: I simply unpackage deezer's own client for window, apply some patches so that it works well under linux, and package it again... I do not add any functionality, and this is not the goal of the project anyway.

@vvitez is very probably right about the API, I have opened deezer's page about it once, and it seemed to be about song metadata only -- so no way to play a song.

This project won't be changed to the point that I make my own client, so I close this. I would love to do it to be honest (using GTK4 and rust, hehe) but I have no time, and that would be an entirely new project anyway! (and quite illegal, since I would be scraping songs as I can't use the API...)
