### ISSUE TITLE
Deezer flatpak hangs on exit.

### ISSUE THREAD

**Issue by Arup65** [aunetx/deezer-linux#71]
On quitting the app, Deezer hangs on exit and has to be manually shut down via system monitor. The system is on a fresh install of Arch Gnome.

![Screenshot from 2024-08-06 08-48-29](https://github.com/user-attachments/assets/ddaba8f4-3557-4e51-949c-06dcff8589ae)

**Comment by Meincrakker** [comment]
Hi @Arup65,

I think this behaviour is intended. When closed the client will continue running until it has been forced to close by the menu in your screenshot or by the system-tray. This is because the client should not stop playing music, when the main window is closed/hidden.

To get a tray in gnome install [this](https://extensions.gnome.org/extension/615/appindicator-support/) extension.

**Comment by Arup65** [comment]
Many thanks, working fine now as per your suggestion, it was nothing major but an annoyance, and thankfully it's gone.
